export const CHANGE_USER = "CHANGE_USER";
export const REQUEST_INFO_PENDING = "REQUEST_INFO_PENDING";
export const REQUEST_INFO_SUCCESS = "REQUEST_INFO_SUCCESS";
export const REQUEST_INFO_FAILED = "REQUEST_INFO_FAILED";
export const REQUEST_REPO_PENDING = "REQUEST_REPO_PENDING";
export const REQUEST_REPO_SUCCESS = "REQUEST_REPO_SUCCESS";
export const REQUEST_REPO_FAILED = "REQUEST_REPO_FAILED";
